// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// ApiPostLabelForm
    /// </summary>
    public partial class ApiPostLabelForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiPostLabelForm" /> class.
        /// </summary>
        /// <param name="color">The hexadecimal color code for the label, without the leading &#x60;#&#x60;.</param>
        /// <param name="description">description</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public ApiPostLabelForm(Option<string?> color = default, Option<string?> description = default, Option<string?> name = default)
        {
            ColorOption = color;
            DescriptionOption = description;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Color
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ColorOption { get; private set; }

        /// <summary>
        /// The hexadecimal color code for the label, without the leading &#x60;#&#x60;.
        /// </summary>
        /// <value>The hexadecimal color code for the label, without the leading &#x60;#&#x60;.</value>
        [JsonPropertyName("color")]
        public string? Color { get { return this.ColorOption; } set { this.ColorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiPostLabelForm {\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiPostLabelForm" />
    /// </summary>
    public class ApiPostLabelFormJsonConverter : JsonConverter<ApiPostLabelForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiPostLabelForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiPostLabelForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> color = default;
            Option<string?> description = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "color":
                            color = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (color.IsSet && color.Value == null)
                throw new ArgumentNullException(nameof(color), "Property is not nullable for class ApiPostLabelForm.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ApiPostLabelForm.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ApiPostLabelForm.");

            return new ApiPostLabelForm(color, description, name);
        }

        /// <summary>
        /// Serializes a <see cref="ApiPostLabelForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiPostLabelForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiPostLabelForm apiPostLabelForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiPostLabelForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiPostLabelForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiPostLabelForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiPostLabelForm apiPostLabelForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiPostLabelForm.ColorOption.IsSet && apiPostLabelForm.Color == null)
                throw new ArgumentNullException(nameof(apiPostLabelForm.Color), "Property is required for class ApiPostLabelForm.");

            if (apiPostLabelForm.DescriptionOption.IsSet && apiPostLabelForm.Description == null)
                throw new ArgumentNullException(nameof(apiPostLabelForm.Description), "Property is required for class ApiPostLabelForm.");

            if (apiPostLabelForm.NameOption.IsSet && apiPostLabelForm.Name == null)
                throw new ArgumentNullException(nameof(apiPostLabelForm.Name), "Property is required for class ApiPostLabelForm.");

            if (apiPostLabelForm.ColorOption.IsSet)
                writer.WriteString("color", apiPostLabelForm.Color);

            if (apiPostLabelForm.DescriptionOption.IsSet)
                writer.WriteString("description", apiPostLabelForm.Description);

            if (apiPostLabelForm.NameOption.IsSet)
                writer.WriteString("name", apiPostLabelForm.Name);
        }
    }
}
