// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// Defines constant.RepoStatus
    /// </summary>
    public enum ConstantRepoStatus
    {
        /// <summary>
        /// Enum RepoStatusOK for value: 0
        /// </summary>
        RepoStatusOK = 0,

        /// <summary>
        /// Enum RepoStatusArchived for value: 1
        /// </summary>
        RepoStatusArchived = 1,

        /// <summary>
        /// Enum RepoStatusForking for value: 2
        /// </summary>
        RepoStatusForking = 2
    }

    /// <summary>
    /// Converts <see cref="ConstantRepoStatus"/> to and from the JSON value
    /// </summary>
    public static class ConstantRepoStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ConstantRepoStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConstantRepoStatus FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return ConstantRepoStatus.RepoStatusOK;

            if (value.Equals((1).ToString()))
                return ConstantRepoStatus.RepoStatusArchived;

            if (value.Equals((2).ToString()))
                return ConstantRepoStatus.RepoStatusForking;

            throw new NotImplementedException($"Could not convert value to type ConstantRepoStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ConstantRepoStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConstantRepoStatus? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return ConstantRepoStatus.RepoStatusOK;

            if (value.Equals((1).ToString()))
                return ConstantRepoStatus.RepoStatusArchived;

            if (value.Equals((2).ToString()))
                return ConstantRepoStatus.RepoStatusForking;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ConstantRepoStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(ConstantRepoStatus value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConstantRepoStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ConstantRepoStatusJsonConverter : JsonConverter<ConstantRepoStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ConstantRepoStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ConstantRepoStatus? result = rawValue == null
                ? null
                : ConstantRepoStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ConstantRepoStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="constantRepoStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ConstantRepoStatus constantRepoStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(constantRepoStatus.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConstantRepoStatus"/>
    /// </summary>
    public class ConstantRepoStatusNullableJsonConverter : JsonConverter<ConstantRepoStatus?>
    {
        /// <summary>
        /// Returns a ConstantRepoStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ConstantRepoStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ConstantRepoStatus? result = rawValue == null
                ? null
                : ConstantRepoStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="constantRepoStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ConstantRepoStatus? constantRepoStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(constantRepoStatus?.ToString() ?? "null");
        }
    }
}
