// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// DtoNpmTagDetail
    /// </summary>
    public partial class DtoNpmTagDetail : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoNpmTagDetail" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="dependencies">dependencies</param>
        /// <param name="desc">desc</param>
        /// <param name="files">files</param>
        /// <param name="lastPusher">lastPusher</param>
        /// <param name="package">package</param>
        /// <param name="pullCount">pullCount</param>
        /// <param name="recentPullCount">recentPullCount</param>
        /// <param name="size">size</param>
        /// <param name="slug">slug</param>
        /// <param name="status">status</param>
        /// <param name="tag">tag</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public DtoNpmTagDetail(Option<string?> address = default, Option<List<DtoDependency>?> dependencies = default, Option<string?> desc = default, Option<List<DtoFile>?> files = default, Option<DtoLastPusher?> lastPusher = default, Option<string?> package = default, Option<int?> pullCount = default, Option<int?> recentPullCount = default, Option<int?> size = default, Option<string?> slug = default, Option<string?> status = default, Option<string?> tag = default, Option<List<DtoNpmTag>?> tags = default)
        {
            AddressOption = address;
            DependenciesOption = dependencies;
            DescOption = desc;
            FilesOption = files;
            LastPusherOption = lastPusher;
            PackageOption = package;
            PullCountOption = pullCount;
            RecentPullCountOption = recentPullCount;
            SizeOption = size;
            SlugOption = slug;
            StatusOption = status;
            TagOption = tag;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string? Address { get { return this.AddressOption; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Dependencies
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DtoDependency>?> DependenciesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Dependencies
        /// </summary>
        [JsonPropertyName("dependencies")]
        public List<DtoDependency>? Dependencies { get { return this.DependenciesOption; } set { this.DependenciesOption = new(value); } }

        /// <summary>
        /// Used to track the state of Desc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescOption { get; private set; }

        /// <summary>
        /// Gets or Sets Desc
        /// </summary>
        [JsonPropertyName("desc")]
        public string? Desc { get { return this.DescOption; } set { this.DescOption = new(value); } }

        /// <summary>
        /// Used to track the state of Files
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DtoFile>?> FilesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [JsonPropertyName("files")]
        public List<DtoFile>? Files { get { return this.FilesOption; } set { this.FilesOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastPusher
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DtoLastPusher?> LastPusherOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastPusher
        /// </summary>
        [JsonPropertyName("last_pusher")]
        public DtoLastPusher? LastPusher { get { return this.LastPusherOption; } set { this.LastPusherOption = new(value); } }

        /// <summary>
        /// Used to track the state of Package
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PackageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Package
        /// </summary>
        [JsonPropertyName("package")]
        public string? Package { get { return this.PackageOption; } set { this.PackageOption = new(value); } }

        /// <summary>
        /// Used to track the state of PullCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PullCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets PullCount
        /// </summary>
        [JsonPropertyName("pull_count")]
        public int? PullCount { get { return this.PullCountOption; } set { this.PullCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of RecentPullCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> RecentPullCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets RecentPullCount
        /// </summary>
        [JsonPropertyName("recent_pull_count")]
        public int? RecentPullCount { get { return this.RecentPullCountOption; } set { this.RecentPullCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Size
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [JsonPropertyName("size")]
        public int? Size { get { return this.SizeOption; } set { this.SizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Slug
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SlugOption { get; private set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        [JsonPropertyName("slug")]
        public string? Slug { get { return this.SlugOption; } set { this.SlugOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tag
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TagOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tag
        /// </summary>
        [JsonPropertyName("tag")]
        public string? Tag { get { return this.TagOption; } set { this.TagOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DtoNpmTag>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<DtoNpmTag>? Tags { get { return this.TagsOption; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoNpmTagDetail {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Dependencies: ").Append(Dependencies).Append("\n");
            sb.Append("  Desc: ").Append(Desc).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  LastPusher: ").Append(LastPusher).Append("\n");
            sb.Append("  Package: ").Append(Package).Append("\n");
            sb.Append("  PullCount: ").Append(PullCount).Append("\n");
            sb.Append("  RecentPullCount: ").Append(RecentPullCount).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoNpmTagDetail" />
    /// </summary>
    public class DtoNpmTagDetailJsonConverter : JsonConverter<DtoNpmTagDetail>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoNpmTagDetail" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoNpmTagDetail Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> address = default;
            Option<List<DtoDependency>?> dependencies = default;
            Option<string?> desc = default;
            Option<List<DtoFile>?> files = default;
            Option<DtoLastPusher?> lastPusher = default;
            Option<string?> package = default;
            Option<int?> pullCount = default;
            Option<int?> recentPullCount = default;
            Option<int?> size = default;
            Option<string?> slug = default;
            Option<string?> status = default;
            Option<string?> tag = default;
            Option<List<DtoNpmTag>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "dependencies":
                            dependencies = new Option<List<DtoDependency>?>(JsonSerializer.Deserialize<List<DtoDependency>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "desc":
                            desc = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "files":
                            files = new Option<List<DtoFile>?>(JsonSerializer.Deserialize<List<DtoFile>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "last_pusher":
                            lastPusher = new Option<DtoLastPusher?>(JsonSerializer.Deserialize<DtoLastPusher>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "package":
                            package = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "pull_count":
                            pullCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "recent_pull_count":
                            recentPullCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "size":
                            size = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "slug":
                            slug = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tag":
                            tag = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tags":
                            tags = new Option<List<DtoNpmTag>?>(JsonSerializer.Deserialize<List<DtoNpmTag>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class DtoNpmTagDetail.");

            if (dependencies.IsSet && dependencies.Value == null)
                throw new ArgumentNullException(nameof(dependencies), "Property is not nullable for class DtoNpmTagDetail.");

            if (desc.IsSet && desc.Value == null)
                throw new ArgumentNullException(nameof(desc), "Property is not nullable for class DtoNpmTagDetail.");

            if (files.IsSet && files.Value == null)
                throw new ArgumentNullException(nameof(files), "Property is not nullable for class DtoNpmTagDetail.");

            if (lastPusher.IsSet && lastPusher.Value == null)
                throw new ArgumentNullException(nameof(lastPusher), "Property is not nullable for class DtoNpmTagDetail.");

            if (package.IsSet && package.Value == null)
                throw new ArgumentNullException(nameof(package), "Property is not nullable for class DtoNpmTagDetail.");

            if (pullCount.IsSet && pullCount.Value == null)
                throw new ArgumentNullException(nameof(pullCount), "Property is not nullable for class DtoNpmTagDetail.");

            if (recentPullCount.IsSet && recentPullCount.Value == null)
                throw new ArgumentNullException(nameof(recentPullCount), "Property is not nullable for class DtoNpmTagDetail.");

            if (size.IsSet && size.Value == null)
                throw new ArgumentNullException(nameof(size), "Property is not nullable for class DtoNpmTagDetail.");

            if (slug.IsSet && slug.Value == null)
                throw new ArgumentNullException(nameof(slug), "Property is not nullable for class DtoNpmTagDetail.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class DtoNpmTagDetail.");

            if (tag.IsSet && tag.Value == null)
                throw new ArgumentNullException(nameof(tag), "Property is not nullable for class DtoNpmTagDetail.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class DtoNpmTagDetail.");

            return new DtoNpmTagDetail(address, dependencies, desc, files, lastPusher, package, pullCount, recentPullCount, size, slug, status, tag, tags);
        }

        /// <summary>
        /// Serializes a <see cref="DtoNpmTagDetail" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoNpmTagDetail"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoNpmTagDetail dtoNpmTagDetail, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoNpmTagDetail, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoNpmTagDetail" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoNpmTagDetail"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoNpmTagDetail dtoNpmTagDetail, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoNpmTagDetail.AddressOption.IsSet && dtoNpmTagDetail.Address == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Address), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.DependenciesOption.IsSet && dtoNpmTagDetail.Dependencies == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Dependencies), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.DescOption.IsSet && dtoNpmTagDetail.Desc == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Desc), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.FilesOption.IsSet && dtoNpmTagDetail.Files == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Files), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.LastPusherOption.IsSet && dtoNpmTagDetail.LastPusher == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.LastPusher), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.PackageOption.IsSet && dtoNpmTagDetail.Package == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Package), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.SlugOption.IsSet && dtoNpmTagDetail.Slug == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Slug), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.StatusOption.IsSet && dtoNpmTagDetail.Status == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Status), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.TagOption.IsSet && dtoNpmTagDetail.Tag == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Tag), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.TagsOption.IsSet && dtoNpmTagDetail.Tags == null)
                throw new ArgumentNullException(nameof(dtoNpmTagDetail.Tags), "Property is required for class DtoNpmTagDetail.");

            if (dtoNpmTagDetail.AddressOption.IsSet)
                writer.WriteString("address", dtoNpmTagDetail.Address);

            if (dtoNpmTagDetail.DependenciesOption.IsSet)
            {
                writer.WritePropertyName("dependencies");
                JsonSerializer.Serialize(writer, dtoNpmTagDetail.Dependencies, jsonSerializerOptions);
            }
            if (dtoNpmTagDetail.DescOption.IsSet)
                writer.WriteString("desc", dtoNpmTagDetail.Desc);

            if (dtoNpmTagDetail.FilesOption.IsSet)
            {
                writer.WritePropertyName("files");
                JsonSerializer.Serialize(writer, dtoNpmTagDetail.Files, jsonSerializerOptions);
            }
            if (dtoNpmTagDetail.LastPusherOption.IsSet)
            {
                writer.WritePropertyName("last_pusher");
                JsonSerializer.Serialize(writer, dtoNpmTagDetail.LastPusher, jsonSerializerOptions);
            }
            if (dtoNpmTagDetail.PackageOption.IsSet)
                writer.WriteString("package", dtoNpmTagDetail.Package);

            if (dtoNpmTagDetail.PullCountOption.IsSet)
                writer.WriteNumber("pull_count", dtoNpmTagDetail.PullCountOption.Value!.Value);

            if (dtoNpmTagDetail.RecentPullCountOption.IsSet)
                writer.WriteNumber("recent_pull_count", dtoNpmTagDetail.RecentPullCountOption.Value!.Value);

            if (dtoNpmTagDetail.SizeOption.IsSet)
                writer.WriteNumber("size", dtoNpmTagDetail.SizeOption.Value!.Value);

            if (dtoNpmTagDetail.SlugOption.IsSet)
                writer.WriteString("slug", dtoNpmTagDetail.Slug);

            if (dtoNpmTagDetail.StatusOption.IsSet)
                writer.WriteString("status", dtoNpmTagDetail.Status);

            if (dtoNpmTagDetail.TagOption.IsSet)
                writer.WriteString("tag", dtoNpmTagDetail.Tag);

            if (dtoNpmTagDetail.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, dtoNpmTagDetail.Tags, jsonSerializerOptions);
            }
        }
    }
}
