// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// DtoQuotaRsp
    /// </summary>
    public partial class DtoQuotaRsp : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DtoQuotaRsp" /> class.
        /// </summary>
        /// <param name="hard">The hard limits of the quota,example: { \&quot;hard\&quot;: { \&quot;storage\&quot;: -1}}</param>
        /// <param name="repositoryName">The repository name of the quota</param>
        /// <param name="storagePerProject">The cnb default quota value</param>
        /// <param name="used">The used limits of the quota,example: { \&quot;used\&quot;: { \&quot;storage\&quot;: 0}}</param>
        [JsonConstructor]
        public DtoQuotaRsp(Option<DtoStorage?> hard = default, Option<string?> repositoryName = default, Option<string?> storagePerProject = default, Option<DtoStorage?> used = default)
        {
            HardOption = hard;
            RepositoryNameOption = repositoryName;
            StoragePerProjectOption = storagePerProject;
            UsedOption = used;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Hard
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DtoStorage?> HardOption { get; private set; }

        /// <summary>
        /// The hard limits of the quota,example: { \&quot;hard\&quot;: { \&quot;storage\&quot;: -1}}
        /// </summary>
        /// <value>The hard limits of the quota,example: { \&quot;hard\&quot;: { \&quot;storage\&quot;: -1}}</value>
        [JsonPropertyName("hard")]
        public DtoStorage? Hard { get { return this.HardOption; } set { this.HardOption = new(value); } }

        /// <summary>
        /// Used to track the state of RepositoryName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RepositoryNameOption { get; private set; }

        /// <summary>
        /// The repository name of the quota
        /// </summary>
        /// <value>The repository name of the quota</value>
        [JsonPropertyName("repository_name")]
        public string? RepositoryName { get { return this.RepositoryNameOption; } set { this.RepositoryNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of StoragePerProject
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StoragePerProjectOption { get; private set; }

        /// <summary>
        /// The cnb default quota value
        /// </summary>
        /// <value>The cnb default quota value</value>
        [JsonPropertyName("storage_per_project")]
        public string? StoragePerProject { get { return this.StoragePerProjectOption; } set { this.StoragePerProjectOption = new(value); } }

        /// <summary>
        /// Used to track the state of Used
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DtoStorage?> UsedOption { get; private set; }

        /// <summary>
        /// The used limits of the quota,example: { \&quot;used\&quot;: { \&quot;storage\&quot;: 0}}
        /// </summary>
        /// <value>The used limits of the quota,example: { \&quot;used\&quot;: { \&quot;storage\&quot;: 0}}</value>
        [JsonPropertyName("used")]
        public DtoStorage? Used { get { return this.UsedOption; } set { this.UsedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DtoQuotaRsp {\n");
            sb.Append("  Hard: ").Append(Hard).Append("\n");
            sb.Append("  RepositoryName: ").Append(RepositoryName).Append("\n");
            sb.Append("  StoragePerProject: ").Append(StoragePerProject).Append("\n");
            sb.Append("  Used: ").Append(Used).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DtoQuotaRsp" />
    /// </summary>
    public class DtoQuotaRspJsonConverter : JsonConverter<DtoQuotaRsp>
    {
        /// <summary>
        /// Deserializes json to <see cref="DtoQuotaRsp" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DtoQuotaRsp Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DtoStorage?> hard = default;
            Option<string?> repositoryName = default;
            Option<string?> storagePerProject = default;
            Option<DtoStorage?> used = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hard":
                            hard = new Option<DtoStorage?>(JsonSerializer.Deserialize<DtoStorage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "repository_name":
                            repositoryName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "storage_per_project":
                            storagePerProject = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "used":
                            used = new Option<DtoStorage?>(JsonSerializer.Deserialize<DtoStorage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (hard.IsSet && hard.Value == null)
                throw new ArgumentNullException(nameof(hard), "Property is not nullable for class DtoQuotaRsp.");

            if (repositoryName.IsSet && repositoryName.Value == null)
                throw new ArgumentNullException(nameof(repositoryName), "Property is not nullable for class DtoQuotaRsp.");

            if (storagePerProject.IsSet && storagePerProject.Value == null)
                throw new ArgumentNullException(nameof(storagePerProject), "Property is not nullable for class DtoQuotaRsp.");

            if (used.IsSet && used.Value == null)
                throw new ArgumentNullException(nameof(used), "Property is not nullable for class DtoQuotaRsp.");

            return new DtoQuotaRsp(hard, repositoryName, storagePerProject, used);
        }

        /// <summary>
        /// Serializes a <see cref="DtoQuotaRsp" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoQuotaRsp"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DtoQuotaRsp dtoQuotaRsp, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, dtoQuotaRsp, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DtoQuotaRsp" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dtoQuotaRsp"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DtoQuotaRsp dtoQuotaRsp, JsonSerializerOptions jsonSerializerOptions)
        {
            if (dtoQuotaRsp.HardOption.IsSet && dtoQuotaRsp.Hard == null)
                throw new ArgumentNullException(nameof(dtoQuotaRsp.Hard), "Property is required for class DtoQuotaRsp.");

            if (dtoQuotaRsp.RepositoryNameOption.IsSet && dtoQuotaRsp.RepositoryName == null)
                throw new ArgumentNullException(nameof(dtoQuotaRsp.RepositoryName), "Property is required for class DtoQuotaRsp.");

            if (dtoQuotaRsp.StoragePerProjectOption.IsSet && dtoQuotaRsp.StoragePerProject == null)
                throw new ArgumentNullException(nameof(dtoQuotaRsp.StoragePerProject), "Property is required for class DtoQuotaRsp.");

            if (dtoQuotaRsp.UsedOption.IsSet && dtoQuotaRsp.Used == null)
                throw new ArgumentNullException(nameof(dtoQuotaRsp.Used), "Property is required for class DtoQuotaRsp.");

            if (dtoQuotaRsp.HardOption.IsSet)
            {
                writer.WritePropertyName("hard");
                JsonSerializer.Serialize(writer, dtoQuotaRsp.Hard, jsonSerializerOptions);
            }
            if (dtoQuotaRsp.RepositoryNameOption.IsSet)
                writer.WriteString("repository_name", dtoQuotaRsp.RepositoryName);

            if (dtoQuotaRsp.StoragePerProjectOption.IsSet)
                writer.WriteString("storage_per_project", dtoQuotaRsp.StoragePerProject);

            if (dtoQuotaRsp.UsedOption.IsSet)
            {
                writer.WritePropertyName("used");
                JsonSerializer.Serialize(writer, dtoQuotaRsp.Used, jsonSerializerOptions);
            }
        }
    }
}
