// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// OpenapiCommitAssetUploadURL
    /// </summary>
    public partial class OpenapiCommitAssetUploadURL : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenapiCommitAssetUploadURL" /> class.
        /// </summary>
        /// <param name="expiresInSec">expiresInSec</param>
        /// <param name="uploadUrl">uploadUrl</param>
        /// <param name="verifyUrl">verifyUrl</param>
        [JsonConstructor]
        public OpenapiCommitAssetUploadURL(Option<int?> expiresInSec = default, Option<string?> uploadUrl = default, Option<string?> verifyUrl = default)
        {
            ExpiresInSecOption = expiresInSec;
            UploadUrlOption = uploadUrl;
            VerifyUrlOption = verifyUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ExpiresInSec
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ExpiresInSecOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresInSec
        /// </summary>
        [JsonPropertyName("expires_in_sec")]
        public int? ExpiresInSec { get { return this.ExpiresInSecOption; } set { this.ExpiresInSecOption = new(value); } }

        /// <summary>
        /// Used to track the state of UploadUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UploadUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets UploadUrl
        /// </summary>
        [JsonPropertyName("upload_url")]
        public string? UploadUrl { get { return this.UploadUrlOption; } set { this.UploadUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of VerifyUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VerifyUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets VerifyUrl
        /// </summary>
        [JsonPropertyName("verify_url")]
        public string? VerifyUrl { get { return this.VerifyUrlOption; } set { this.VerifyUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OpenapiCommitAssetUploadURL {\n");
            sb.Append("  ExpiresInSec: ").Append(ExpiresInSec).Append("\n");
            sb.Append("  UploadUrl: ").Append(UploadUrl).Append("\n");
            sb.Append("  VerifyUrl: ").Append(VerifyUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OpenapiCommitAssetUploadURL" />
    /// </summary>
    public class OpenapiCommitAssetUploadURLJsonConverter : JsonConverter<OpenapiCommitAssetUploadURL>
    {
        /// <summary>
        /// Deserializes json to <see cref="OpenapiCommitAssetUploadURL" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OpenapiCommitAssetUploadURL Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> expiresInSec = default;
            Option<string?> uploadUrl = default;
            Option<string?> verifyUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "expires_in_sec":
                            expiresInSec = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "upload_url":
                            uploadUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "verify_url":
                            verifyUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (expiresInSec.IsSet && expiresInSec.Value == null)
                throw new ArgumentNullException(nameof(expiresInSec), "Property is not nullable for class OpenapiCommitAssetUploadURL.");

            if (uploadUrl.IsSet && uploadUrl.Value == null)
                throw new ArgumentNullException(nameof(uploadUrl), "Property is not nullable for class OpenapiCommitAssetUploadURL.");

            if (verifyUrl.IsSet && verifyUrl.Value == null)
                throw new ArgumentNullException(nameof(verifyUrl), "Property is not nullable for class OpenapiCommitAssetUploadURL.");

            return new OpenapiCommitAssetUploadURL(expiresInSec, uploadUrl, verifyUrl);
        }

        /// <summary>
        /// Serializes a <see cref="OpenapiCommitAssetUploadURL" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openapiCommitAssetUploadURL"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OpenapiCommitAssetUploadURL openapiCommitAssetUploadURL, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, openapiCommitAssetUploadURL, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OpenapiCommitAssetUploadURL" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openapiCommitAssetUploadURL"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OpenapiCommitAssetUploadURL openapiCommitAssetUploadURL, JsonSerializerOptions jsonSerializerOptions)
        {
            if (openapiCommitAssetUploadURL.UploadUrlOption.IsSet && openapiCommitAssetUploadURL.UploadUrl == null)
                throw new ArgumentNullException(nameof(openapiCommitAssetUploadURL.UploadUrl), "Property is required for class OpenapiCommitAssetUploadURL.");

            if (openapiCommitAssetUploadURL.VerifyUrlOption.IsSet && openapiCommitAssetUploadURL.VerifyUrl == null)
                throw new ArgumentNullException(nameof(openapiCommitAssetUploadURL.VerifyUrl), "Property is required for class OpenapiCommitAssetUploadURL.");

            if (openapiCommitAssetUploadURL.ExpiresInSecOption.IsSet)
                writer.WriteNumber("expires_in_sec", openapiCommitAssetUploadURL.ExpiresInSecOption.Value!.Value);

            if (openapiCommitAssetUploadURL.UploadUrlOption.IsSet)
                writer.WriteString("upload_url", openapiCommitAssetUploadURL.UploadUrl);

            if (openapiCommitAssetUploadURL.VerifyUrlOption.IsSet)
                writer.WriteString("verify_url", openapiCommitAssetUploadURL.VerifyUrl);
        }
    }
}
