// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// WebapiHeadRef
    /// </summary>
    public partial class WebapiHeadRef : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebapiHeadRef" /> class.
        /// </summary>
        /// <param name="ref">ref</param>
        [JsonConstructor]
        public WebapiHeadRef(Option<string?> @ref = default)
        {
            RefOption = @ref;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Ref
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefOption { get; private set; }

        /// <summary>
        /// Gets or Sets Ref
        /// </summary>
        [JsonPropertyName("ref")]
        public string? Ref { get { return this.RefOption; } set { this.RefOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebapiHeadRef {\n");
            sb.Append("  Ref: ").Append(Ref).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebapiHeadRef" />
    /// </summary>
    public class WebapiHeadRefJsonConverter : JsonConverter<WebapiHeadRef>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebapiHeadRef" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebapiHeadRef Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> varRef = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ref":
                            varRef = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (varRef.IsSet && varRef.Value == null)
                throw new ArgumentNullException(nameof(varRef), "Property is not nullable for class WebapiHeadRef.");

            return new WebapiHeadRef(varRef);
        }

        /// <summary>
        /// Serializes a <see cref="WebapiHeadRef" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webapiHeadRef"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebapiHeadRef webapiHeadRef, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webapiHeadRef, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebapiHeadRef" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webapiHeadRef"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebapiHeadRef webapiHeadRef, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webapiHeadRef.RefOption.IsSet && webapiHeadRef.Ref == null)
                throw new ArgumentNullException(nameof(webapiHeadRef.Ref), "Property is required for class WebapiHeadRef.");

            if (webapiHeadRef.RefOption.IsSet)
                writer.WriteString("ref", webapiHeadRef.Ref);
        }
    }
}
