// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// WebapiUpdateCodeSensitiveIgnoreForm
    /// </summary>
    public partial class WebapiUpdateCodeSensitiveIgnoreForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebapiUpdateCodeSensitiveIgnoreForm" /> class.
        /// </summary>
        /// <param name="ignore">ignore</param>
        /// <param name="ignoreReason">ignoreReason</param>
        [JsonConstructor]
        public WebapiUpdateCodeSensitiveIgnoreForm(Option<bool?> ignore = default, Option<string?> ignoreReason = default)
        {
            IgnoreOption = ignore;
            IgnoreReasonOption = ignoreReason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Ignore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IgnoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets Ignore
        /// </summary>
        [JsonPropertyName("ignore")]
        public bool? Ignore { get { return this.IgnoreOption; } set { this.IgnoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of IgnoreReason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IgnoreReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets IgnoreReason
        /// </summary>
        [JsonPropertyName("ignore_reason")]
        public string? IgnoreReason { get { return this.IgnoreReasonOption; } set { this.IgnoreReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebapiUpdateCodeSensitiveIgnoreForm {\n");
            sb.Append("  Ignore: ").Append(Ignore).Append("\n");
            sb.Append("  IgnoreReason: ").Append(IgnoreReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebapiUpdateCodeSensitiveIgnoreForm" />
    /// </summary>
    public class WebapiUpdateCodeSensitiveIgnoreFormJsonConverter : JsonConverter<WebapiUpdateCodeSensitiveIgnoreForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebapiUpdateCodeSensitiveIgnoreForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebapiUpdateCodeSensitiveIgnoreForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> ignore = default;
            Option<string?> ignoreReason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ignore":
                            ignore = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "ignore_reason":
                            ignoreReason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (ignore.IsSet && ignore.Value == null)
                throw new ArgumentNullException(nameof(ignore), "Property is not nullable for class WebapiUpdateCodeSensitiveIgnoreForm.");

            if (ignoreReason.IsSet && ignoreReason.Value == null)
                throw new ArgumentNullException(nameof(ignoreReason), "Property is not nullable for class WebapiUpdateCodeSensitiveIgnoreForm.");

            return new WebapiUpdateCodeSensitiveIgnoreForm(ignore, ignoreReason);
        }

        /// <summary>
        /// Serializes a <see cref="WebapiUpdateCodeSensitiveIgnoreForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webapiUpdateCodeSensitiveIgnoreForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebapiUpdateCodeSensitiveIgnoreForm webapiUpdateCodeSensitiveIgnoreForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webapiUpdateCodeSensitiveIgnoreForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebapiUpdateCodeSensitiveIgnoreForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webapiUpdateCodeSensitiveIgnoreForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebapiUpdateCodeSensitiveIgnoreForm webapiUpdateCodeSensitiveIgnoreForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webapiUpdateCodeSensitiveIgnoreForm.IgnoreReasonOption.IsSet && webapiUpdateCodeSensitiveIgnoreForm.IgnoreReason == null)
                throw new ArgumentNullException(nameof(webapiUpdateCodeSensitiveIgnoreForm.IgnoreReason), "Property is required for class WebapiUpdateCodeSensitiveIgnoreForm.");

            if (webapiUpdateCodeSensitiveIgnoreForm.IgnoreOption.IsSet)
                writer.WriteBoolean("ignore", webapiUpdateCodeSensitiveIgnoreForm.IgnoreOption.Value!.Value);

            if (webapiUpdateCodeSensitiveIgnoreForm.IgnoreReasonOption.IsSet)
                writer.WriteString("ignore_reason", webapiUpdateCodeSensitiveIgnoreForm.IgnoreReason);
        }
    }
}
