// <auto-generated>
/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using CNBOpenApi.Client;

namespace CNBOpenApi.Model
{
    /// <summary>
    /// WebMissionResources
    /// </summary>
    public partial class WebMissionResources : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebMissionResources" /> class.
        /// </summary>
        /// <param name="issues">issues</param>
        /// <param name="pullRequests">pullRequests</param>
        [JsonConstructor]
        public WebMissionResources(Option<List<WebIssueResource>?> issues = default, Option<List<WebPullRequestResource>?> pullRequests = default)
        {
            IssuesOption = issues;
            PullRequestsOption = pullRequests;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Issues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<WebIssueResource>?> IssuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Issues
        /// </summary>
        [JsonPropertyName("issues")]
        public List<WebIssueResource>? Issues { get { return this.IssuesOption; } set { this.IssuesOption = new(value); } }

        /// <summary>
        /// Used to track the state of PullRequests
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<WebPullRequestResource>?> PullRequestsOption { get; private set; }

        /// <summary>
        /// Gets or Sets PullRequests
        /// </summary>
        [JsonPropertyName("pull_requests")]
        public List<WebPullRequestResource>? PullRequests { get { return this.PullRequestsOption; } set { this.PullRequestsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebMissionResources {\n");
            sb.Append("  Issues: ").Append(Issues).Append("\n");
            sb.Append("  PullRequests: ").Append(PullRequests).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebMissionResources" />
    /// </summary>
    public class WebMissionResourcesJsonConverter : JsonConverter<WebMissionResources>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebMissionResources" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebMissionResources Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<WebIssueResource>?> issues = default;
            Option<List<WebPullRequestResource>?> pullRequests = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "issues":
                            issues = new Option<List<WebIssueResource>?>(JsonSerializer.Deserialize<List<WebIssueResource>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pull_requests":
                            pullRequests = new Option<List<WebPullRequestResource>?>(JsonSerializer.Deserialize<List<WebPullRequestResource>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (issues.IsSet && issues.Value == null)
                throw new ArgumentNullException(nameof(issues), "Property is not nullable for class WebMissionResources.");

            if (pullRequests.IsSet && pullRequests.Value == null)
                throw new ArgumentNullException(nameof(pullRequests), "Property is not nullable for class WebMissionResources.");

            return new WebMissionResources(issues, pullRequests);
        }

        /// <summary>
        /// Serializes a <see cref="WebMissionResources" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webMissionResources"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebMissionResources webMissionResources, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webMissionResources, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebMissionResources" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webMissionResources"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebMissionResources webMissionResources, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webMissionResources.IssuesOption.IsSet && webMissionResources.Issues == null)
                throw new ArgumentNullException(nameof(webMissionResources.Issues), "Property is required for class WebMissionResources.");

            if (webMissionResources.PullRequestsOption.IsSet && webMissionResources.PullRequests == null)
                throw new ArgumentNullException(nameof(webMissionResources.PullRequests), "Property is required for class WebMissionResources.");

            if (webMissionResources.IssuesOption.IsSet)
            {
                writer.WritePropertyName("issues");
                JsonSerializer.Serialize(writer, webMissionResources.Issues, jsonSerializerOptions);
            }
            if (webMissionResources.PullRequestsOption.IsSet)
            {
                writer.WritePropertyName("pull_requests");
                JsonSerializer.Serialize(writer, webMissionResources.PullRequests, jsonSerializerOptions);
            }
        }
    }
}
