/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing ApiPatchPullRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiPatchPullRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiPatchPullRequest
        //private ApiPatchPullRequest instance;

        public ApiPatchPullRequestTests()
        {
            // TODO uncomment below to create an instance of ApiPatchPullRequest
            //instance = new ApiPatchPullRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiPatchPullRequest
        /// </summary>
        [Fact]
        public void ApiPatchPullRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiPatchPullRequest
            //Assert.IsType<ApiPatchPullRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
    }
}
