/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing ConstantRepoDisplayModule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConstantRepoDisplayModuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConstantRepoDisplayModule
        //private ConstantRepoDisplayModule instance;

        public ConstantRepoDisplayModuleTests()
        {
            // TODO uncomment below to create an instance of ConstantRepoDisplayModule
            //instance = new ConstantRepoDisplayModule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConstantRepoDisplayModule
        /// </summary>
        [Fact]
        public void ConstantRepoDisplayModuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConstantRepoDisplayModule
            //Assert.IsType<ConstantRepoDisplayModule>(instance);
        }
    }
}
