/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoArtifactStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoArtifactStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoArtifactStatus
        //private DtoArtifactStatus instance;

        public DtoArtifactStatusTests()
        {
            // TODO uncomment below to create an instance of DtoArtifactStatus
            //instance = new DtoArtifactStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoArtifactStatus
        /// </summary>
        [Fact]
        public void DtoArtifactStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoArtifactStatus
            //Assert.IsType<DtoArtifactStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
