/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoLastPusher
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoLastPusherTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoLastPusher
        //private DtoLastPusher instance;

        public DtoLastPusherTests()
        {
            // TODO uncomment below to create an instance of DtoLastPusher
            //instance = new DtoLastPusher();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoLastPusher
        /// </summary>
        [Fact]
        public void DtoLastPusherInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoLastPusher
            //Assert.IsType<DtoLastPusher>(instance);
        }

        /// <summary>
        /// Test the property 'IsFrozen'
        /// </summary>
        [Fact]
        public void IsFrozenTest()
        {
            // TODO unit test for the property 'IsFrozen'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Fact]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }

        /// <summary>
        /// Test the property 'PushAt'
        /// </summary>
        [Fact]
        public void PushAtTest()
        {
            // TODO unit test for the property 'PushAt'
        }
    }
}
