/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoPackage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoPackageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoPackage
        //private DtoPackage instance;

        public DtoPackageTests()
        {
            // TODO uncomment below to create an instance of DtoPackage
            //instance = new DtoPackage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoPackage
        /// </summary>
        [Fact]
        public void DtoPackageInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoPackage
            //Assert.IsType<DtoPackage>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'LastArtifactName'
        /// </summary>
        [Fact]
        public void LastArtifactNameTest()
        {
            // TODO unit test for the property 'LastArtifactName'
        }

        /// <summary>
        /// Test the property 'LastPusher'
        /// </summary>
        [Fact]
        public void LastPusherTest()
        {
            // TODO unit test for the property 'LastPusher'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Package'
        /// </summary>
        [Fact]
        public void PackageTest()
        {
            // TODO unit test for the property 'Package'
        }

        /// <summary>
        /// Test the property 'PackageType'
        /// </summary>
        [Fact]
        public void PackageTypeTest()
        {
            // TODO unit test for the property 'PackageType'
        }

        /// <summary>
        /// Test the property 'PullCount'
        /// </summary>
        [Fact]
        public void PullCountTest()
        {
            // TODO unit test for the property 'PullCount'
        }

        /// <summary>
        /// Test the property 'RecentPullCount'
        /// </summary>
        [Fact]
        public void RecentPullCountTest()
        {
            // TODO unit test for the property 'RecentPullCount'
        }
    }
}
