/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoRegistry4User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoRegistry4UserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoRegistry4User
        //private DtoRegistry4User instance;

        public DtoRegistry4UserTests()
        {
            // TODO uncomment below to create an instance of DtoRegistry4User
            //instance = new DtoRegistry4User();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoRegistry4User
        /// </summary>
        [Fact]
        public void DtoRegistry4UserInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoRegistry4User
            //Assert.IsType<DtoRegistry4User>(instance);
        }

        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Fact]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }

        /// <summary>
        /// Test the property 'ArtifactPolicy'
        /// </summary>
        [Fact]
        public void ArtifactPolicyTest()
        {
            // TODO unit test for the property 'ArtifactPolicy'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Freeze'
        /// </summary>
        [Fact]
        public void FreezeTest()
        {
            // TODO unit test for the property 'Freeze'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'LastPushTime'
        /// </summary>
        [Fact]
        public void LastPushTimeTest()
        {
            // TODO unit test for the property 'LastPushTime'
        }

        /// <summary>
        /// Test the property 'LastPushUser'
        /// </summary>
        [Fact]
        public void LastPushUserTest()
        {
            // TODO unit test for the property 'LastPushUser'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OverwritePolicy'
        /// </summary>
        [Fact]
        public void OverwritePolicyTest()
        {
            // TODO unit test for the property 'OverwritePolicy'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'PkgCount'
        /// </summary>
        [Fact]
        public void PkgCountTest()
        {
            // TODO unit test for the property 'PkgCount'
        }

        /// <summary>
        /// Test the property 'StarTime'
        /// </summary>
        [Fact]
        public void StarTimeTest()
        {
            // TODO unit test for the property 'StarTime'
        }

        /// <summary>
        /// Test the property 'Stared'
        /// </summary>
        [Fact]
        public void StaredTest()
        {
            // TODO unit test for the property 'Stared'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'UsedSize'
        /// </summary>
        [Fact]
        public void UsedSizeTest()
        {
            // TODO unit test for the property 'UsedSize'
        }

        /// <summary>
        /// Test the property 'VisibilityLevel'
        /// </summary>
        [Fact]
        public void VisibilityLevelTest()
        {
            // TODO unit test for the property 'VisibilityLevel'
        }
    }
}
