/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoResourceMission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoResourceMissionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoResourceMission
        //private DtoResourceMission instance;

        public DtoResourceMissionTests()
        {
            // TODO uncomment below to create an instance of DtoResourceMission
            //instance = new DtoResourceMission();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoResourceMission
        /// </summary>
        [Fact]
        public void DtoResourceMissionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoResourceMission
            //Assert.IsType<DtoResourceMission>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Freeze'
        /// </summary>
        [Fact]
        public void FreezeTest()
        {
            // TODO unit test for the property 'Freeze'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'VisibilityLevel'
        /// </summary>
        [Fact]
        public void VisibilityLevelTest()
        {
            // TODO unit test for the property 'VisibilityLevel'
        }
    }
}
