/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoStartBuildReq
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoStartBuildReqTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoStartBuildReq
        //private DtoStartBuildReq instance;

        public DtoStartBuildReqTests()
        {
            // TODO uncomment below to create an instance of DtoStartBuildReq
            //instance = new DtoStartBuildReq();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoStartBuildReq
        /// </summary>
        [Fact]
        public void DtoStartBuildReqInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoStartBuildReq
            //Assert.IsType<DtoStartBuildReq>(instance);
        }

        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Fact]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'Env'
        /// </summary>
        [Fact]
        public void EnvTest()
        {
            // TODO unit test for the property 'Env'
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Sha'
        /// </summary>
        [Fact]
        public void ShaTest()
        {
            // TODO unit test for the property 'Sha'
        }

        /// <summary>
        /// Test the property 'Sync'
        /// </summary>
        [Fact]
        public void SyncTest()
        {
            // TODO unit test for the property 'Sync'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
    }
}
