/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoUserEmailWithCodePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoUserEmailWithCodePayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoUserEmailWithCodePayload
        //private DtoUserEmailWithCodePayload instance;

        public DtoUserEmailWithCodePayloadTests()
        {
            // TODO uncomment below to create an instance of DtoUserEmailWithCodePayload
            //instance = new DtoUserEmailWithCodePayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoUserEmailWithCodePayload
        /// </summary>
        [Fact]
        public void DtoUserEmailWithCodePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoUserEmailWithCodePayload
            //Assert.IsType<DtoUserEmailWithCodePayload>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
