/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing DtoWorkspaceListResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DtoWorkspaceListResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DtoWorkspaceListResult
        //private DtoWorkspaceListResult instance;

        public DtoWorkspaceListResultTests()
        {
            // TODO uncomment below to create an instance of DtoWorkspaceListResult
            //instance = new DtoWorkspaceListResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DtoWorkspaceListResult
        /// </summary>
        [Fact]
        public void DtoWorkspaceListResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" DtoWorkspaceListResult
            //Assert.IsType<DtoWorkspaceListResult>(instance);
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }

        /// <summary>
        /// Test the property 'PageInfo'
        /// </summary>
        [Fact]
        public void PageInfoTest()
        {
            // TODO unit test for the property 'PageInfo'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
