/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing OpenapiCommitAssetUploadURL
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenapiCommitAssetUploadURLTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenapiCommitAssetUploadURL
        //private OpenapiCommitAssetUploadURL instance;

        public OpenapiCommitAssetUploadURLTests()
        {
            // TODO uncomment below to create an instance of OpenapiCommitAssetUploadURL
            //instance = new OpenapiCommitAssetUploadURL();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenapiCommitAssetUploadURL
        /// </summary>
        [Fact]
        public void OpenapiCommitAssetUploadURLInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpenapiCommitAssetUploadURL
            //Assert.IsType<OpenapiCommitAssetUploadURL>(instance);
        }

        /// <summary>
        /// Test the property 'ExpiresInSec'
        /// </summary>
        [Fact]
        public void ExpiresInSecTest()
        {
            // TODO unit test for the property 'ExpiresInSec'
        }

        /// <summary>
        /// Test the property 'UploadUrl'
        /// </summary>
        [Fact]
        public void UploadUrlTest()
        {
            // TODO unit test for the property 'UploadUrl'
        }

        /// <summary>
        /// Test the property 'VerifyUrl'
        /// </summary>
        [Fact]
        public void VerifyUrlTest()
        {
            // TODO unit test for the property 'VerifyUrl'
        }
    }
}
