/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing OpenapiPostReleaseForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenapiPostReleaseFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenapiPostReleaseForm
        //private OpenapiPostReleaseForm instance;

        public OpenapiPostReleaseFormTests()
        {
            // TODO uncomment below to create an instance of OpenapiPostReleaseForm
            //instance = new OpenapiPostReleaseForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenapiPostReleaseForm
        /// </summary>
        [Fact]
        public void OpenapiPostReleaseFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpenapiPostReleaseForm
            //Assert.IsType<OpenapiPostReleaseForm>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Fact]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }

        /// <summary>
        /// Test the property 'MakeLatest'
        /// </summary>
        [Fact]
        public void MakeLatestTest()
        {
            // TODO unit test for the property 'MakeLatest'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Prerelease'
        /// </summary>
        [Fact]
        public void PrereleaseTest()
        {
            // TODO unit test for the property 'Prerelease'
        }

        /// <summary>
        /// Test the property 'TagName'
        /// </summary>
        [Fact]
        public void TagNameTest()
        {
            // TODO unit test for the property 'TagName'
        }

        /// <summary>
        /// Test the property 'TargetCommitish'
        /// </summary>
        [Fact]
        public void TargetCommitishTest()
        {
            // TODO unit test for the property 'TargetCommitish'
        }
    }
}
