/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing ScopeGroupItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScopeGroupItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScopeGroupItem
        //private ScopeGroupItem instance;

        public ScopeGroupItemTests()
        {
            // TODO uncomment below to create an instance of ScopeGroupItem
            //instance = new ScopeGroupItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScopeGroupItem
        /// </summary>
        [Fact]
        public void ScopeGroupItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScopeGroupItem
            //Assert.IsType<ScopeGroupItem>(instance);
        }

        /// <summary>
        /// Test the property 'Codes'
        /// </summary>
        [Fact]
        public void CodesTest()
        {
            // TODO unit test for the property 'Codes'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
    }
}
