/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing V1Descriptor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1DescriptorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1Descriptor
        //private V1Descriptor instance;

        public V1DescriptorTests()
        {
            // TODO uncomment below to create an instance of V1Descriptor
            //instance = new V1Descriptor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1Descriptor
        /// </summary>
        [Fact]
        public void V1DescriptorInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1Descriptor
            //Assert.IsType<V1Descriptor>(instance);
        }

        /// <summary>
        /// Test the property 'Annotations'
        /// </summary>
        [Fact]
        public void AnnotationsTest()
        {
            // TODO unit test for the property 'Annotations'
        }

        /// <summary>
        /// Test the property 'ArtifactType'
        /// </summary>
        [Fact]
        public void ArtifactTypeTest()
        {
            // TODO unit test for the property 'ArtifactType'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Digest'
        /// </summary>
        [Fact]
        public void DigestTest()
        {
            // TODO unit test for the property 'Digest'
        }

        /// <summary>
        /// Test the property 'MediaType'
        /// </summary>
        [Fact]
        public void MediaTypeTest()
        {
            // TODO unit test for the property 'MediaType'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Fact]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }
    }
}
