/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebapiCreateTagForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebapiCreateTagFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebapiCreateTagForm
        //private WebapiCreateTagForm instance;

        public WebapiCreateTagFormTests()
        {
            // TODO uncomment below to create an instance of WebapiCreateTagForm
            //instance = new WebapiCreateTagForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebapiCreateTagForm
        /// </summary>
        [Fact]
        public void WebapiCreateTagFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebapiCreateTagForm
            //Assert.IsType<WebapiCreateTagForm>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
    }
}
