/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebapiPullRequestNumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebapiPullRequestNumberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebapiPullRequestNumber
        //private WebapiPullRequestNumber instance;

        public WebapiPullRequestNumberTests()
        {
            // TODO uncomment below to create an instance of WebapiPullRequestNumber
            //instance = new WebapiPullRequestNumber();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebapiPullRequestNumber
        /// </summary>
        [Fact]
        public void WebapiPullRequestNumberInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebapiPullRequestNumber
            //Assert.IsType<WebapiPullRequestNumber>(instance);
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
    }
}
