/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebContributorTrend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebContributorTrendTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebContributorTrend
        //private WebContributorTrend instance;

        public WebContributorTrendTests()
        {
            // TODO uncomment below to create an instance of WebContributorTrend
            //instance = new WebContributorTrend();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebContributorTrend
        /// </summary>
        [Fact]
        public void WebContributorTrendInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebContributorTrend
            //Assert.IsType<WebContributorTrend>(instance);
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'CommitCount'
        /// </summary>
        [Fact]
        public void CommitCountTest()
        {
            // TODO unit test for the property 'CommitCount'
        }

        /// <summary>
        /// Test the property 'Weeks'
        /// </summary>
        [Fact]
        public void WeeksTest()
        {
            // TODO unit test for the property 'Weeks'
        }
    }
}
