/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebIssueComment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebIssueCommentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebIssueComment
        //private WebIssueComment instance;

        public WebIssueCommentTests()
        {
            // TODO uncomment below to create an instance of WebIssueComment
            //instance = new WebIssueComment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebIssueComment
        /// </summary>
        [Fact]
        public void WebIssueCommentInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebIssueComment
            //Assert.IsType<WebIssueComment>(instance);
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'AuthorMeta'
        /// </summary>
        [Fact]
        public void AuthorMetaTest()
        {
            // TODO unit test for the property 'AuthorMeta'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'CommentId'
        /// </summary>
        [Fact]
        public void CommentIdTest()
        {
            // TODO unit test for the property 'CommentId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
