/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNBOpenApi.Model;
using CNBOpenApi.Client;
using System.Reflection;

namespace CNBOpenApi.Test.Model
{
    /// <summary>
    ///  Class for testing WebPullViewedFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebPullViewedFileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebPullViewedFile
        //private WebPullViewedFile instance;

        public WebPullViewedFileTests()
        {
            // TODO uncomment below to create an instance of WebPullViewedFile
            //instance = new WebPullViewedFile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebPullViewedFile
        /// </summary>
        [Fact]
        public void WebPullViewedFileInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebPullViewedFile
            //Assert.IsType<WebPullViewedFile>(instance);
        }

        /// <summary>
        /// Test the property 'HeadCommitSha'
        /// </summary>
        [Fact]
        public void HeadCommitShaTest()
        {
            // TODO unit test for the property 'HeadCommitSha'
        }

        /// <summary>
        /// Test the property 'IsViewed'
        /// </summary>
        [Fact]
        public void IsViewedTest()
        {
            // TODO unit test for the property 'IsViewed'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
    }
}
