/*
 * CNB OPENAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: cnb@tencent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using CNBOpenApi.Api;
using CNBOpenApi.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace CNBOpenApi.Test.Api
{
    /// <summary>
    ///  Class for testing ContributorsApi
    /// </summary>
    public sealed class ContributorsApiTests : ApiTestsBase
    {
        private readonly IContributorsApi _instance;

        public ContributorsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IContributorsApi>();
        }

        /// <summary>
        /// Test GetMemberAccessLevelOfGroup
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMemberAccessLevelOfGroupAsyncTest()
        {
            string group = default!;
            Client.Option<bool> includeInherit = default!;
            var response = await _instance.GetMemberAccessLevelOfGroupAsync(group, includeInherit);
            var model = response.Ok();
            Assert.IsType<DtoMemberAccessLevelInSlugUnion>(model);
        }

        /// <summary>
        /// Test GetMemberAccessLevelOfRepo
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMemberAccessLevelOfRepoAsyncTest()
        {
            string repo = default!;
            Client.Option<bool> includeInherit = default!;
            var response = await _instance.GetMemberAccessLevelOfRepoAsync(repo, includeInherit);
            var model = response.Ok();
            Assert.IsType<DtoMemberAccessLevelInSlugUnion>(model);
        }

        /// <summary>
        /// Test ListMemberAccessLevelOfGroup
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMemberAccessLevelOfGroupAsyncTest()
        {
            string group = default!;
            string username = default!;
            var response = await _instance.ListMemberAccessLevelOfGroupAsync(group, username);
            var model = response.Ok();
            Assert.IsType<List<DtoMemberAccessLevel>>(model);
        }

        /// <summary>
        /// Test ListMemberAccessLevelOfRepo
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListMemberAccessLevelOfRepoAsyncTest()
        {
            string repo = default!;
            string username = default!;
            var response = await _instance.ListMemberAccessLevelOfRepoAsync(repo, username);
            var model = response.Ok();
            Assert.IsType<List<DtoMemberAccessLevel>>(model);
        }
    }
}
